export enum ActionType {
  GET_MOVIES = 'GET_MOVIES',
  LOAD_MOVIES = 'LOAD_MOVIES',
  SHOW_MOVIE_DETAILS_MODAL = 'SHOW_MOVIE_DETAILS_MODAL',
  SHOW_MODAL = 'SHOW_MODAL',
  LOAD_GENRES = 'LOAD_GENRES',
  GET_RANDOM_MOVIE_ID = 'GET_RANDOM_MOVIE_ID',
  GET_MOVIE_DETAILS = 'GET_MOVIE_DETAILS',
  GET_MOVIE_IMAGES = 'GET_MOVIE_IMAGES',
  SHOW_RANDOM_MOVIE_DETAILS = 'SHOW_RANDOM_MOVIE_DETAILS',
  SET_GENRE_ID = 'SET_GENRE_ID',
  SHOW_DETAILS = 'SHOW_DETAILS',
}
